"""add_genre_ids_to_library_item

Revision ID: 14681e7064e4
Revises: 8db9a4988a8b
Create Date: 2026-05-05 17:09:05.331215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14681e7064e4'
down_revision: Union[str, Sequence[str], None] = '8db9a4988a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_item', sa.Column('genre_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_item', 'genre_ids')
    # ### end Alembic commands ###
