"""add is_spoiler to comment

Revision ID: 4147d585d551
Revises: 5747cdd762bb
Create Date: 2026-04-30 23:47:28.899866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4147d585d551'
down_revision: Union[str, Sequence[str], None] = '5747cdd762bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_spoiler', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_spoiler')
    # ### end Alembic commands ###
