"""cleanup_metadata_redundancy

Revision ID: 53a24e462ae7
Revises: 14681e7064e4
Create Date: 2026-05-08 23:46:29.723374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53a24e462ae7'
down_revision: Union[str, Sequence[str], None] = '14681e7064e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_list_item', 'poster_path')
    op.drop_column('custom_list_item', 'title')
    op.drop_column('follow', 'followed_person_name')
    op.drop_column('follow', 'followed_person_image')
    op.drop_column('library_item', 'poster_path')
    op.drop_column('library_item', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_item', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('library_item', sa.Column('poster_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('follow', sa.Column('followed_person_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('follow', sa.Column('followed_person_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('custom_list_item', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('custom_list_item', sa.Column('poster_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
