"""Add avatar_url to user

Revision ID: 5747cdd762bb
Revises: 5df68122fd05
Create Date: 2026-04-28 15:57:18.765773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5747cdd762bb'
down_revision: Union[str, Sequence[str], None] = '5df68122fd05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('commentinteraction_comment_id_fkey'), 'commentinteraction', type_='foreignkey')
    op.create_foreign_key(None, 'commentinteraction', 'comment', ['comment_id'], ['id'])
    op.drop_constraint(op.f('notification_comment_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'comment', ['comment_id'], ['id'])
    op.add_column('user', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('user_supabase_id_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_supabase_id'), 'user', ['supabase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_supabase_id'), table_name='user')
    op.create_unique_constraint(op.f('user_supabase_id_key'), 'user', ['supabase_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'avatar_url')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_comment_id_fkey'), 'notification', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'commentinteraction', type_='foreignkey')
    op.create_foreign_key(op.f('commentinteraction_comment_id_fkey'), 'commentinteraction', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
