"""unify library items

Revision ID: 8db9a4988a8b
Revises: 9ba5bc895b4a
Create Date: 2026-05-05 16:22:47.497154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8db9a4988a8b'
down_revision: Union[str, Sequence[str], None] = '9ba5bc895b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('poster_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('release_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_watchlist', sa.Boolean(), nullable=False),
    sa.Column('is_watched', sa.Boolean(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=False),
    sa.Column('is_disliked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_item_is_disliked'), 'library_item', ['is_disliked'], unique=False)
    op.create_index(op.f('ix_library_item_is_liked'), 'library_item', ['is_liked'], unique=False)
    op.create_index(op.f('ix_library_item_is_watched'), 'library_item', ['is_watched'], unique=False)
    op.create_index(op.f('ix_library_item_is_watchlist'), 'library_item', ['is_watchlist'], unique=False)
    op.create_index(op.f('ix_library_item_media_type'), 'library_item', ['media_type'], unique=False)
    op.create_index(op.f('ix_library_item_tmdb_id'), 'library_item', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_library_item_user_id'), 'library_item', ['user_id'], unique=False)
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_interaction_interaction_type'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_user_id'), table_name='interaction')
    op.drop_table('interaction')
    op.alter_column('custom_list', 'slug',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_index(op.f('ix_custom_list_slug'), 'custom_list', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_list_slug'), table_name='custom_list')
    op.alter_column('custom_list', 'slug',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_table('interaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('poster_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vote_average', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genre_ids', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('interaction_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interaction_pkey'))
    )
    op.create_index(op.f('ix_interaction_user_id'), 'interaction', ['user_id'], unique=False)
    op.create_index(op.f('ix_interaction_interaction_type'), 'interaction', ['interaction_type'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('poster_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vote_average', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genre_ids', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('watchlist_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('watchlist_pkey'))
    )
    op.drop_index(op.f('ix_library_item_user_id'), table_name='library_item')
    op.drop_index(op.f('ix_library_item_tmdb_id'), table_name='library_item')
    op.drop_index(op.f('ix_library_item_media_type'), table_name='library_item')
    op.drop_index(op.f('ix_library_item_is_watchlist'), table_name='library_item')
    op.drop_index(op.f('ix_library_item_is_watched'), table_name='library_item')
    op.drop_index(op.f('ix_library_item_is_liked'), table_name='library_item')
    op.drop_index(op.f('ix_library_item_is_disliked'), table_name='library_item')
    op.drop_table('library_item')
    # ### end Alembic commands ###
