"""add is_complete to user

Revision ID: 9e722716fb7c
Revises: d88b778f8c32
Create Date: 2026-04-24 20:02:00.772137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e722716fb7c'
down_revision: Union[str, Sequence[str], None] = 'd88b778f8c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_complete', sa.Boolean(), nullable=False))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('user_supabase_id_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_supabase_id'), 'user', ['supabase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_supabase_id'), table_name='user')
    op.create_unique_constraint(op.f('user_supabase_id_key'), 'user', ['supabase_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'is_complete')
    # ### end Alembic commands ###
