"""add_person_details_to_follow

Revision ID: d88b778f8c32
Revises: 867bc7efcf65
Create Date: 2026-04-22 02:23:58.828007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd88b778f8c32'
down_revision: Union[str, Sequence[str], None] = '867bc7efcf65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('followed_person_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('follow', sa.Column('followed_person_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow', 'followed_person_image')
    op.drop_column('follow', 'followed_person_name')
    # ### end Alembic commands ###
